services:
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - ENV=development

      # Database credentials
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=jarvis-database-1
      - DATABASE_NAME=peachtree_development

      # Redis credentials
      - REDIS_URL=jarvis-redis-1
      - REDIS_PORT=6379

      - JWT_KEY=byebye
      - SESSION_KEY=helluu

    depends_on:
      - database
      - redis

    volumes:
      - ./backend:/usr/src/app/

  database:
    restart: always
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - peachtree-database-data:/var/lib/postgresql/data
  
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - '8081:8081'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    environment:
      - NODE_ENV=development
      - PORT=8081
      - MODE=web  # android / ios

    depends_on:
      - backend
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - jarvis-redis-data:/data

volumes:
  peachtree-database-data:  # NOTE: CHANGE THAT
    external: true
  jarvis-redis-data:
    external: true