// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/calendar"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CalendarUpdate is the builder for updating Calendar entities.
type CalendarUpdate struct {
	config
	hooks    []Hook
	mutation *CalendarMutation
}

// Where appends a list predicates to the CalendarUpdate builder.
func (cu *CalendarUpdate) Where(ps ...predicate.Calendar) *CalendarUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "name" field.
func (cu *CalendarUpdate) SetName(s string) *CalendarUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetType sets the "type" field.
func (cu *CalendarUpdate) SetType(s string) *CalendarUpdate {
	cu.mutation.SetType(s)
	return cu
}

// SetToken sets the "token" field.
func (cu *CalendarUpdate) SetToken(s string) *CalendarUpdate {
	cu.mutation.SetToken(s)
	return cu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (cu *CalendarUpdate) SetNillableToken(s *string) *CalendarUpdate {
	if s != nil {
		cu.SetToken(*s)
	}
	return cu
}

// ClearToken clears the value of the "token" field.
func (cu *CalendarUpdate) ClearToken() *CalendarUpdate {
	cu.mutation.ClearToken()
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CalendarUpdate) SetCreatedAt(t time.Time) *CalendarUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CalendarUpdate) SetNillableCreatedAt(t *time.Time) *CalendarUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cu *CalendarUpdate) SetUserID(id int) *CalendarUpdate {
	cu.mutation.SetUserID(id)
	return cu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (cu *CalendarUpdate) SetNillableUserID(id *int) *CalendarUpdate {
	if id != nil {
		cu = cu.SetUserID(*id)
	}
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *CalendarUpdate) SetUser(u *User) *CalendarUpdate {
	return cu.SetUserID(u.ID)
}

// Mutation returns the CalendarMutation object of the builder.
func (cu *CalendarUpdate) Mutation() *CalendarMutation {
	return cu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cu *CalendarUpdate) ClearUser() *CalendarUpdate {
	cu.mutation.ClearUser()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CalendarUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CalendarUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CalendarUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CalendarUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *CalendarUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(calendar.Table, calendar.Columns, sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(calendar.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.GetType(); ok {
		_spec.SetField(calendar.FieldType, field.TypeString, value)
	}
	if value, ok := cu.mutation.Token(); ok {
		_spec.SetField(calendar.FieldToken, field.TypeString, value)
	}
	if cu.mutation.TokenCleared() {
		_spec.ClearField(calendar.FieldToken, field.TypeString)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(calendar.FieldCreatedAt, field.TypeTime, value)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendar.UserTable,
			Columns: []string{calendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendar.UserTable,
			Columns: []string{calendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CalendarUpdateOne is the builder for updating a single Calendar entity.
type CalendarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CalendarMutation
}

// SetName sets the "name" field.
func (cuo *CalendarUpdateOne) SetName(s string) *CalendarUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetType sets the "type" field.
func (cuo *CalendarUpdateOne) SetType(s string) *CalendarUpdateOne {
	cuo.mutation.SetType(s)
	return cuo
}

// SetToken sets the "token" field.
func (cuo *CalendarUpdateOne) SetToken(s string) *CalendarUpdateOne {
	cuo.mutation.SetToken(s)
	return cuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (cuo *CalendarUpdateOne) SetNillableToken(s *string) *CalendarUpdateOne {
	if s != nil {
		cuo.SetToken(*s)
	}
	return cuo
}

// ClearToken clears the value of the "token" field.
func (cuo *CalendarUpdateOne) ClearToken() *CalendarUpdateOne {
	cuo.mutation.ClearToken()
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CalendarUpdateOne) SetCreatedAt(t time.Time) *CalendarUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CalendarUpdateOne) SetNillableCreatedAt(t *time.Time) *CalendarUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (cuo *CalendarUpdateOne) SetUserID(id int) *CalendarUpdateOne {
	cuo.mutation.SetUserID(id)
	return cuo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (cuo *CalendarUpdateOne) SetNillableUserID(id *int) *CalendarUpdateOne {
	if id != nil {
		cuo = cuo.SetUserID(*id)
	}
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *CalendarUpdateOne) SetUser(u *User) *CalendarUpdateOne {
	return cuo.SetUserID(u.ID)
}

// Mutation returns the CalendarMutation object of the builder.
func (cuo *CalendarUpdateOne) Mutation() *CalendarMutation {
	return cuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *CalendarUpdateOne) ClearUser() *CalendarUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// Where appends a list predicates to the CalendarUpdate builder.
func (cuo *CalendarUpdateOne) Where(ps ...predicate.Calendar) *CalendarUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CalendarUpdateOne) Select(field string, fields ...string) *CalendarUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Calendar entity.
func (cuo *CalendarUpdateOne) Save(ctx context.Context) (*Calendar, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CalendarUpdateOne) SaveX(ctx context.Context) *Calendar {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CalendarUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CalendarUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *CalendarUpdateOne) sqlSave(ctx context.Context) (_node *Calendar, err error) {
	_spec := sqlgraph.NewUpdateSpec(calendar.Table, calendar.Columns, sqlgraph.NewFieldSpec(calendar.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Calendar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, calendar.FieldID)
		for _, f := range fields {
			if !calendar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != calendar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(calendar.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.GetType(); ok {
		_spec.SetField(calendar.FieldType, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Token(); ok {
		_spec.SetField(calendar.FieldToken, field.TypeString, value)
	}
	if cuo.mutation.TokenCleared() {
		_spec.ClearField(calendar.FieldToken, field.TypeString)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(calendar.FieldCreatedAt, field.TypeTime, value)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendar.UserTable,
			Columns: []string{calendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   calendar.UserTable,
			Columns: []string{calendar.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Calendar{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{calendar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
